# -*- mode: ruby -*-
# vi: set ft=ruby :

# Provider variable: Set to "libvirt" (KVM) or "virtualbox"
# Can also be set via environment variable: export VAGRANT_DEFAULT_PROVIDER=libvirt
PROVIDER = ENV['VAGRANT_DEFAULT_PROVIDER'] || "libvirt"

machines=[
  {
    :hostname => "nmunirS",
    :ip => "192.168.56.110",
    :box => "generic/alpine319",
    :ram => 1024,
    :cpu => 1,
    :script => "./scripts/nmunirS_provision.sh"
  }
]

Vagrant.configure("2") do |config|

  machines.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]

      node.vm.synced_folder "./confs", "/vagrant/confs"

      # KVM / Libvirt Provider Config (Primary)
      node.vm.provider "libvirt" do |lv|
        lv.memory = machine[:ram]
        lv.cpus = machine[:cpu]
      end

      # VirtualBox Provider Config (Fallback)
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end

      node.vm.provision "shell", path: machine[:script]
    end
  end
end
  