# -*- mode: ruby -*-
# vi: set ft=ruby :

PROVIDER = ENV['VAGRANT_DEFAULT_PROVIDER'] || "libvirt"

BOX_IMAGE = "nmunir/alpine"
BOX_URL = (PROVIDER == "virtualbox") ?
  "https://github.com/NomanMunir/vagrant-boxes/releases/download/alpine-v1.0.0/alpine-latest.box" :
  "https://github.com/NomanMunir/vagrant-boxes/releases/download/alpine-v1.0.0/alpine-latest-libvirt.box"

machines = [
  {
    :hostname => "nmunirS",
    :ip       => "192.168.56.110",
    :box      => BOX_IMAGE,
    :box_url  => BOX_URL,
    :ram      => 2048,
    :cpu      => 2,
    :script   => "./scripts/nmunirS_provision.sh"
  }
]

Vagrant.configure("2") do |config|

  machines.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.box_url = machine[:box_url]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]

      node.vm.synced_folder "./confs", "/vagrant/confs", type: "rsync"

      # Libvirt Provider Config (KVM on Linux)
      node.vm.provider "libvirt" do |lv|
        lv.memory = machine[:ram]
        lv.cpus = machine[:cpu]
      end

      # VirtualBox Provider Config (Windows / Mac / Linux)
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end

      node.vm.provision "shell", path: machine[:script]
    end
  end
end