# -*- mode: ruby -*-
# vi: set ft=ruby :

# Load ENV from .env file if it exists
if File.exist?('.env')
  File.readlines('.env').each do |line|
    key, value = line.strip.split('=', 2)
    ENV[key] = value if key && value && !line.start_with?('#')
  end
end

k3s_token = ENV['K3S_TOKEN'] || "default-iot-k3s-token-12345"

Vagrant.configure("2") do |config|

  BOX_IMAGE = "nmunir/alpine"
  BOX_URL   = "https://raw.githubusercontent.com/NomanMunir/vagrant-boxes/main/alpine.json"

  # Libvirt Provider Config (KVM on Linux)
  config.vm.provider "libvirt" do |lv|
    lv.cpus = 1
    lv.memory = 1024
  end

  # VirtualBox Provider Config (Windows / Mac / Linux)
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
  end

  config.vm.box_check_update = false

  # Controller Node (Server)
  config.vm.define "nmunirS" do |server|
    server.vm.box = BOX_IMAGE
    server.vm.box_url = BOX_URL
    server.vm.hostname = "nmunirS"
    
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provision "shell", path: "./scripts/nmunirS_provision.sh", env: {"K3S_TOKEN" => k3s_token}
  end

  # Worker Node (Agent)
  config.vm.define "nmunirSW" do |worker|
    worker.vm.box = BOX_IMAGE
    worker.vm.box_url = BOX_URL
    worker.vm.hostname = "nmunirSW"

    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provision "shell", path: "./scripts/nmunirSW_provision.sh", env: {"K3S_TOKEN" => k3s_token}
  end
end